<a href="https://colab.research.google.com/github/abhi19992/Word-embedding-Techniques/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
  error: subprocess-exited-with-error
  
  × Running setup.py install for tensorflow-gpu did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py install for tensorflow-gpu ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> tensorflow-gpu

note: This is an issue with the package mentioned above, not pip.
hint: See above for outpu

In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

In [19]:
for words in sent:
  print(words)

the glass of milk
the glass of juice
the cup of tea
I am a good boy
I am a good developer
understand the meaning of words
your videos are good


#### One Hot Representation

In [9]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[224, 189, 322, 356], [224, 189, 322, 88], [224, 305, 322, 156], [253, 130, 110, 236, 301], [253, 130, 110, 236, 486], [475, 224, 187, 322, 211], [218, 155, 166, 236]]


### Word Embedding Represntation

In [20]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [21]:
import numpy as np

In [22]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 224 189 322 356]
 [  0   0   0   0 224 189 322  88]
 [  0   0   0   0 224 305 322 156]
 [  0   0   0 253 130 110 236 301]
 [  0   0   0 253 130 110 236 486]
 [  0   0   0 475 224 187 322 211]
 [  0   0   0   0 218 155 166 236]]


In [23]:
## 10 feature dimesnions
dim=10


In [24]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [26]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 224, 189, 322, 356], dtype=int32)

In [27]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 167ms/step


array([[-0.01485896, -0.02017902,  0.02684532, -0.01998472, -0.0221321 ,
         0.00655091, -0.00476276, -0.02635622, -0.04453437,  0.01752963],
       [-0.01485896, -0.02017902,  0.02684532, -0.01998472, -0.0221321 ,
         0.00655091, -0.00476276, -0.02635622, -0.04453437,  0.01752963],
       [-0.01485896, -0.02017902,  0.02684532, -0.01998472, -0.0221321 ,
         0.00655091, -0.00476276, -0.02635622, -0.04453437,  0.01752963],
       [-0.01485896, -0.02017902,  0.02684532, -0.01998472, -0.0221321 ,
         0.00655091, -0.00476276, -0.02635622, -0.04453437,  0.01752963],
       [ 0.01771394, -0.02547144,  0.01733268,  0.04778082,  0.01624341,
        -0.02332412, -0.02629685, -0.00035576, -0.03390198, -0.02170842],
       [-0.03548602,  0.03361007,  0.00482144, -0.00563413, -0.04277164,
         0.03826493,  0.04417076, -0.03915819,  0.02270235, -0.02798408],
       [ 0.00192933,  0.01001908, -0.04835625,  0.04329062,  0.02901671,
         0.0432708 , -0.04931339, -0.04824153

In [28]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 49ms/step
[[[-1.48589611e-02 -2.01790221e-02  2.68453248e-02 -1.99847221e-02
   -2.21320987e-02  6.55090809e-03 -4.76275757e-03 -2.63562202e-02
   -4.45343740e-02  1.75296329e-02]
  [-1.48589611e-02 -2.01790221e-02  2.68453248e-02 -1.99847221e-02
   -2.21320987e-02  6.55090809e-03 -4.76275757e-03 -2.63562202e-02
   -4.45343740e-02  1.75296329e-02]
  [-1.48589611e-02 -2.01790221e-02  2.68453248e-02 -1.99847221e-02
   -2.21320987e-02  6.55090809e-03 -4.76275757e-03 -2.63562202e-02
   -4.45343740e-02  1.75296329e-02]
  [-1.48589611e-02 -2.01790221e-02  2.68453248e-02 -1.99847221e-02
   -2.21320987e-02  6.55090809e-03 -4.76275757e-03 -2.63562202e-02
   -4.45343740e-02  1.75296329e-02]
  [ 1.77139379e-02 -2.54714377e-02  1.73326842e-02  4.77808155e-02
    1.62434094e-02 -2.33241208e-02 -2.62968540e-02 -3.55757773e-04
   -3.39019783e-02 -2.17084177e-02]
  [-3.54860201e-02  3.36100720e-02  4.82144207e-03 -5.63412905e-03
   -4.27716374e-02  3.82649340e

In [29]:
embedded_docs[0]

array([  0,   0,   0,   0, 224, 189, 322, 356], dtype=int32)

In [30]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[-0.01485896 -0.02017902  0.02684532 -0.01998472 -0.0221321   0.00655091
  -0.00476276 -0.02635622 -0.04453437  0.01752963]
 [-0.01485896 -0.02017902  0.02684532 -0.01998472 -0.0221321   0.00655091
  -0.00476276 -0.02635622 -0.04453437  0.01752963]
 [-0.01485896 -0.02017902  0.02684532 -0.01998472 -0.0221321   0.00655091
  -0.00476276 -0.02635622 -0.04453437  0.01752963]
 [-0.01485896 -0.02017902  0.02684532 -0.01998472 -0.0221321   0.00655091
  -0.00476276 -0.02635622 -0.04453437  0.01752963]
 [ 0.01771394 -0.02547144  0.01733268  0.04778082  0.01624341 -0.02332412
  -0.02629685 -0.00035576 -0.03390198 -0.02170842]
 [-0.03548602  0.03361007  0.00482144 -0.00563413 -0.04277164  0.03826493
   0.04417076 -0.03915819  0.02270235 -0.02798408]
 [ 0.00192933  0.01001908 -0.04835625  0.04329062  0.02901671  0.0432708
  -0.04931339 -0.04824153  0.02265849  0.03115146]
 [ 0.00687198 -0.01074358  0.00387838 -0.03361018  0.00112544  0.01291483


In [31]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]